---
hostname: osiris.denbi.de
server_alias: osiris-denbi.galaxyproject.eu

php_memory_limit: "128M"
php_max_execution_time: "60"
php_upload_max_filesize: "128M"
php_packages:
  - php
  - php-cli
  - php-pear
  - php-ldap
  - php-pecl-mongodb

php_webserver_daemon: httpd
php_enablerepo: epel

php_enable_php_fpm: true
php_fpm_state: started
php_fpm_enabled_on_boot: true

osiris_www_dir: /var/www/osiris
osiris_config_file: "{{ osiris_www_dir }}/CONFIG.php"

certbot_bin: "/usr/bin/certbot"
certbot_well_known_root: "{{ osiris_www_dir }}/_well-known_root"
certbot_domains:
  - "{{ hostname }}"
  - "{{ server_alias }}"
certbot_auto_renew_extra:

apache_vhosts:
  - servername: "{{ hostname }}"
    documentroot: "{{ osiris_www_dir }}"
    extra_parameters: |
      Alias /.well-known/acme-challenge/ {{ certbot_well_known_root }}/acme-challenge/
      <Directory "{{ certbot_well_known_root }}">
          Options None
          AllowOverride None
          ForceType text/plain
          Require all granted
      </Directory>
      # Restrict access to .git which we use for updates - https://www.ncsc.admin.ch/git-en
      <Directory "{{ osiris_www_dir }}/.git">
          Options None
          AllowOverride None
          Require all denied
      </Directory>
      ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ osiris_www_dir }}"
  - servername: "{{ server_alias }}"
    documentroot: "{{ osiris_www_dir }}"
    extra_parameters: |
      Alias /.well-known/acme-challenge/ {{ certbot_well_known_root }}/acme-challenge/
      <Directory "{{ certbot_well_known_root }}">
          Options None
          AllowOverride None
          ForceType text/plain
          Require all granted
      </Directory>
      # Restrict access to .git which we use for updates - https://www.ncsc.admin.ch/git-en
      <Directory "{{ osiris_www_dir }}/.git">
          Options None
          AllowOverride None
          Require all denied
      </Directory>
      ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ osiris_www_dir }}"
