---
#- name: "Fix weird tomcat bug"
  #command: "yum reinstall -y tomcat-lib"

- name: Download apollo
  get_url:
    url: "https://usegalaxy.eu/static/vgcn/apollo-{{ apollo_version }}.war"
    dest: "{{ apollo_tmp_file }}"
  register: download

- name: Backup old apollo
  copy:
    src: "{{ tomcat_apollo_webapp_dir }}"
    dest: "/tmp/apollo-backup-{{ ansible_date_time.epoch }}"
    remote_src: true
  when: download.changed
  notify: 'restart tomcat'

- name: Wipe out old apollo
  file:
    path: "{{ tomcat_apollo_webapp_dir }}"
    state: absent
  when: download.changed
  notify: 'restart tomcat'

- name: Make new root webapp
  file:
    path: "{{ tomcat_apollo_webapp_dir }}"
    state: directory
    owner: tomcat
    group: tomcat
  when: download.changed
  notify: 'restart tomcat'

- name: Extract new apollo into root webapp.
  unarchive:
    src: "{{ apollo_tmp_file }}"
    dest: "{{ tomcat_apollo_webapp_dir }}"
    remote_src: true
  when: download.changed
  notify: 'restart tomcat'

- name: Fix perms
  command: "chown tomcat:tomcat -R /usr/share/tomcat/webapps/apollo/"
  when: download.changed
  notify: 'restart tomcat'

- name: Deploy config file
  template:
    src: apollo-config.groovy
    dest: "{{ tomcat_apollo_webapp_dir }}/{{ item }}"
    owner: tomcat
    group: tomcat
    mode: 0640
  with_items:
    #- WEB-INF/classes/java/apollo-config.groovy
    - WEB-INF/classes/apollo-config.groovy
  notify: 'restart tomcat'

- name: Schedule cache cleanup cronjob
  ansible.builtin.cron:
    name: "Tomcat cache cleanup"
    job: "tmpwatch -v -a --mtime --dirmtime 3d {{ tomcat_cache_dir }}"
    user: root
    minute: "0"
    hour: "3"
