---
- name: "Install dependencies for OSIRIS or system use"
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ osiris_dependencies }}"

- name: "Configure restic backups"
  ansible.builtin.include_tasks: configure_restic.yml

- name: "Restore backup from zip"
  ansible.builtin.include_tasks: restore_from_zip.yml
  when: backup_is_zip | default(false) | bool

- name: "Restore backup from restic"
  ansible.builtin.include_tasks: restore_from_restic.yml
  when: not(backup_is_zip | default(false)) | bool

- name: "Use restored backup"
  ansible.builtin.include_tasks: apply_backup_files.yml

- name: "Ensure OSIRIS version matches configuration"
  ansible.builtin.include_tasks: osiris_version.yml

- name: "Configure SELinux for OSIRIS"
  ansible.builtin.include_tasks: selinux.yml

- name: "Delete/Cleanup backup directories"
  ansible.builtin.include_tasks: delete_backup_dir.yml

- name: "Configure certbot and SSL certs"
  ansible.builtin.include_tasks: certbot_ssl.yml

- name: "Notify about need to delete RESTIC files from S3 bucket when restoring from ZIP"
  ansible.builtin.debug:
    msg: "WARNING: You are restoring a backup from ZIP! You need to delete all files/folder but {{ zip_name }} from the S3 bucket {{ s3_host_url }}/{{ s3_bucket }} or RESTIC will not be able to initialize the first backup"
  when: backup_is_zip | bool
